name: ${project.name}
description: ${project.description}
version: ${project.version}
api-version: 1.13

main: com.songoda.ultimatekits.UltimateKits
softdepend:
  - CMI
  - Essentials
  - Holograms
  - HolographicDisplays
  - MiniKitPvP
  - PlaceholderAPI
  - PlayerPoints
  - Reserve
  - UltimateCore
  - Vault

author: Songoda
website: ${project.url}

commands:
  kitadmin:
    description: View information on this plugin.
    default: true
    usage: /<command> [reload]
    aliases:
      - kp
      - uk
      - ultimatekits

  kit:
    description: Preview a kit
    default: true
    usage: /<commands>
    aliases:
      - kits

  previewkit:
    description: Preview a kit
    default: true
    usage: /<command> [kit]
    aliases:
      - pk
      - preview

permissions:
  ultimatekits.use:
    description: allows the user to preview kit
    default: true

  ultimatekits.admin:
    description: Gives access to admin commands.
